title: Easyscoreboards
description: A Sponge plugin to create easily scoreboards for things such as lobbys
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
